/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package keys;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.NoSuchAlgorithmException;

import org.bouncycastle.openpgp.PGPException;

class PGPPainlessUtilTest {
    @Test void appHasAGreeting() throws InvalidAlgorithmParameterException, NoSuchAlgorithmException, PGPException, IOException {
       PGPPainlessUtil pgpPainlessUtil = new PGPPainlessUtil();
       pgpPainlessUtil.createKeyRing();
    }
}
